# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: biblioteca.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'biblioteca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x62iblioteca.proto\x12\nbiblioteca\"$\n\x10VerificarRequest\x12\x10\n\x08livro_id\x18\x01 \x01(\x05\"]\n\x17\x44isponibilidadeResponse\x12\x12\n\ndisponivel\x18\x01 \x01(\x08\x12\x1e\n\x16\x65xemplares_disponiveis\x18\x02 \x01(\x05\x12\x0e\n\x06titulo\x18\x03 \x01(\t\"O\n\x11\x45mprestimoRequest\x12\x10\n\x08livro_id\x18\x01 \x01(\x05\x12\x11\n\tleitor_id\x18\x02 \x01(\x05\x12\x15\n\rdata_prevista\x18\x03 \x01(\t\"N\n\x12\x45mprestimoResponse\x12\x0f\n\x07sucesso\x18\x01 \x01(\x08\x12\x15\n\remprestimo_id\x18\x02 \x01(\x05\x12\x10\n\x08mensagem\x18\x03 \x01(\t2\xc8\x01\n\x11\x42ibliotecaService\x12]\n\x18VerificarDisponibilidade\x12\x1c.biblioteca.VerificarRequest\x1a#.biblioteca.DisponibilidadeResponse\x12T\n\x13RegistrarEmprestimo\x12\x1d.biblioteca.EmprestimoRequest\x1a\x1e.biblioteca.EmprestimoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'biblioteca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VERIFICARREQUEST']._serialized_start=32
  _globals['_VERIFICARREQUEST']._serialized_end=68
  _globals['_DISPONIBILIDADERESPONSE']._serialized_start=70
  _globals['_DISPONIBILIDADERESPONSE']._serialized_end=163
  _globals['_EMPRESTIMOREQUEST']._serialized_start=165
  _globals['_EMPRESTIMOREQUEST']._serialized_end=244
  _globals['_EMPRESTIMORESPONSE']._serialized_start=246
  _globals['_EMPRESTIMORESPONSE']._serialized_end=324
  _globals['_BIBLIOTECASERVICE']._serialized_start=327
  _globals['_BIBLIOTECASERVICE']._serialized_end=527
# @@protoc_insertion_point(module_scope)
