# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import biblioteca_pb2 as biblioteca__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in biblioteca_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BibliotecaServiceStub:
    """─── Serviço principal ───────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VerificarDisponibilidade = channel.unary_unary(
                '/biblioteca.BibliotecaService/VerificarDisponibilidade',
                request_serializer=biblioteca__pb2.VerificarRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.DisponibilidadeResponse.FromString,
                _registered_method=True)
        self.RegistrarEmprestimo = channel.unary_unary(
                '/biblioteca.BibliotecaService/RegistrarEmprestimo',
                request_serializer=biblioteca__pb2.EmprestimoRequest.SerializeToString,
                response_deserializer=biblioteca__pb2.EmprestimoResponse.FromString,
                _registered_method=True)


class BibliotecaServiceServicer:
    """─── Serviço principal ───────────────────────────────────────────────────────

    """

    def VerificarDisponibilidade(self, request, context):
        """Verifica quantos exemplares de um livro estão disponíveis para empréstimo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegistrarEmprestimo(self, request, context):
        """Registra um novo empréstimo no banco de dados
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibliotecaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VerificarDisponibilidade': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarDisponibilidade,
                    request_deserializer=biblioteca__pb2.VerificarRequest.FromString,
                    response_serializer=biblioteca__pb2.DisponibilidadeResponse.SerializeToString,
            ),
            'RegistrarEmprestimo': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistrarEmprestimo,
                    request_deserializer=biblioteca__pb2.EmprestimoRequest.FromString,
                    response_serializer=biblioteca__pb2.EmprestimoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'biblioteca.BibliotecaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('biblioteca.BibliotecaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BibliotecaService:
    """─── Serviço principal ───────────────────────────────────────────────────────

    """

    @staticmethod
    def VerificarDisponibilidade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/VerificarDisponibilidade',
            biblioteca__pb2.VerificarRequest.SerializeToString,
            biblioteca__pb2.DisponibilidadeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegistrarEmprestimo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/biblioteca.BibliotecaService/RegistrarEmprestimo',
            biblioteca__pb2.EmprestimoRequest.SerializeToString,
            biblioteca__pb2.EmprestimoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
